plugins:
  - rubocop-rails
  - rubocop-rspec
  # - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "log/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"
    - ".git/**/*"

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  # EnforcedStyle: double_quotes

Naming/PredicateMethod:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^(\s*#)']

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
    - "app/models/ability.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/*"
    - "config/initializers/*"
    - "app/models/ability.rb"

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

# Naming/MethodParameterName:
#   AllowedNames:
#     - "to"
#     - "at"
#     - "as"

# Style/SafeNavigationChainLength:
#   Max: 3

RSpec/NestedGroups:
  Max: 5

RSpec/ImplicitSubject:
  Enabled: false
